package com.example.readytohelpmobile.model.report

enum class OccurrenceType {
    ANIMAL_ON_ROAD,
    CRIME,
    DOMESTIC_VIOLENCE,
    ELECTRICAL_NETWORK,
    FLOOD,
    FOREST_FIRE,
    INJURED_ANIMAL,
    LANDSLIDE,
    LOST_ANIMAL,
    MEDICAL_EMERGENCY,
    POLLUTION,
    PUBLIC_DISTURBANCE,
    PUBLIC_LIGHTING,
    ROAD_ACCIDENT,
    ROAD_OBSTRUCTION,
    SANITATION,
    TRAFFIC_CONGESTION,
    TRAFFIC_LIGHT_FAILURE,
    URBAN_FIRE,
    VEHICLE_BREAKDOWN,
    WORK_ACCIDENT,
    ROAD_DAMAGE
}